gh-pages action and main connections

diff --git a/bin/pre-push b/bin/pre-push
--- a/bin/pre-push
+++ b/bin/pre-push
@@ -12,12 +12,15 @@ cmp --silent ./.git/hooks/pre-push ./bin/pre-push || echo-and-exit 1 "Error: .gi
 
 echo "Checking the diff for a version update."
 
-current_branch=$(git branch | cut -d ' ' -f2)
-remote_branch="origin/master"
+current_branch=$(git branch | grep "\*" | cut -d ' ' -f2)
+remote_branch="origin/main"
 echo "Comparing current branch: \"$current_branch\" to remote branch: \"$remote_branch\""
 
 line_count=$(git diff "$current_branch".."$remote_branch" ./package.json | egrep '[-+]\s*"version":\s*"\d+\.\d+\.\d+",' | wc -l)
 [[ 2 -eq  $line_count ]] || echo-and-exit 2 "Error: No lines found updating package.json's version."
+
+package_and_lock=$(diff <( < ./package.json sed -n 3p ) <( < ./package-lock.json sed -n 3p ))
+[[ $? -eq 0 ]] || echo-and-exit 3 "Error: package-lock and package versions must be the same."
 
 commit_count=$(git log "$remote_branch".."$current_branch" --oneline | wc -l)
 [[ 1 -eq $commit_count ]] || echo "Warning: Pushing should be squashed into a single commit, saw: \"$commit_count\" commits."
